name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: marius-patrik/DarkFactory/.github/workflows/ci.yml@1e6bdb0e060ea8dbf614bbec1d1fa7b9f3650228
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "1e6bdb0e060ea8dbf614bbec1d1fa7b9f3650228"
    secrets: inherit
