name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: marius-patrik/DarkFactory/.github/workflows/ci.yml@757c89a91f48560e32bbb3315d5b1a1bde8f3cf9
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "757c89a91f48560e32bbb3315d5b1a1bde8f3cf9"
    secrets: inherit
