name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-docs:
    uses: marius-patrik/DarkFactory/.github/workflows/deploy-docs.yml@c61e39e7be5aa882c5f106606a6c0bb1b48348bc
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "c61e39e7be5aa882c5f106606a6c0bb1b48348bc"
    secrets: inherit
