name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-docs:
    uses: marius-patrik/DarkFactory/.github/workflows/deploy-docs.yml@234d84daa826cc3ef775b39009ee36c76ecf57a2
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "234d84daa826cc3ef775b39009ee36c76ecf57a2"
    secrets: inherit
