name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-docs:
    uses: marius-patrik/DarkFactory/.github/workflows/deploy-docs.yml@darkfactory
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "52816adc67cf9327831ecba775e8c9fdde764051"
    secrets: inherit
