name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: marius-patrik/DarkFactory/.github/workflows/release.yml@234d84d9bc24ee246fc0b91d29759c8699b24479
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "234d84d9bc24ee246fc0b91d29759c8699b24479"
    secrets: inherit
