name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: marius-patrik/DarkFactory/.github/workflows/release.yml@c61e39e7be5aa882c5f106606a6c0bb1b48348bc
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "c61e39e7be5aa882c5f106606a6c0bb1b48348bc"
    secrets: inherit
