name: Update Submodules

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    uses: marius-patrik/DarkFactory/.github/workflows/update-submodules.yml@234d84d9bc24ee246fc0b91d29759c8699b24479
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "234d84d9bc24ee246fc0b91d29759c8699b24479"
    secrets: inherit
