name: Update Submodules

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    uses: marius-patrik/DarkFactory/.github/workflows/update-submodules.yml@4f26dd3a4b23e120ac40c94836f3e065d1f82237
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "4f26dd3a4b23e120ac40c94836f3e065d1f82237"
    secrets: inherit
