name: Update Submodules

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    uses: marius-patrik/DarkFactory/.github/workflows/update-submodules.yml@4f26dd372b6c921316b0ee69d2d0b50a2e584f18
    with:
      pipeline-repo: marius-patrik/DarkFactory
      pipeline-ref: "4f26dd372b6c921316b0ee69d2d0b50a2e584f18"
    secrets: inherit
